//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceIDSysR30.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterfaceIDSysR30.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função executada com sucesso.
        /// </summary>
        internal static string RETURN_0 {
            get {
                return ResourceManager.GetString("RETURN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função executada com sucesso e não há registros a serem lidos.
        /// </summary>
        internal static string RETURN_1 {
            get {
                return ResourceManager.GetString("RETURN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função executada com sucesso e chamar a função GetLogType2 para obtenção dos dados.
        /// </summary>
        internal static string RETURN_2 {
            get {
                return ResourceManager.GetString("RETURN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função executada com sucesso e chamar a função GetLogType3 para obtenção dos dados.
        /// </summary>
        internal static string RETURN_3 {
            get {
                return ResourceManager.GetString("RETURN_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função executada com sucesso e chamar a função GetLogType4 para obtenção dos dados.
        /// </summary>
        internal static string RETURN_4 {
            get {
                return ResourceManager.GetString("RETURN_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função executada com sucesso e chamar a função GetLogType5 para obtenção dos dados.
        /// </summary>
        internal static string RETURN_5 {
            get {
                return ResourceManager.GetString("RETURN_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de Proximidade já cadastrado para outro usuário..
        /// </summary>
        internal static string RETURN_NEG_1 {
            get {
                return ResourceManager.GetString("RETURN_NEG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabalhador não cadastrado..
        /// </summary>
        internal static string RETURN_NEG_10 {
            get {
                return ResourceManager.GetString("RETURN_NEG_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no checksum do cabeçalho do pacote..
        /// </summary>
        internal static string RETURN_NEG_100 {
            get {
                return ResourceManager.GetString("RETURN_NEG_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no checksum dos dados do pacote..
        /// </summary>
        internal static string RETURN_NEG_101 {
            get {
                return ResourceManager.GetString("RETURN_NEG_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando inválido..
        /// </summary>
        internal static string RETURN_NEG_102 {
            get {
                return ResourceManager.GetString("RETURN_NEG_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacote inválido. Dados do buffer são inválidos..
        /// </summary>
        internal static string RETURN_NEG_103 {
            get {
                return ResourceManager.GetString("RETURN_NEG_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no tamanho do pacote: pacote vazio..
        /// </summary>
        internal static string RETURN_NEG_104 {
            get {
                return ResourceManager.GetString("RETURN_NEG_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no tamanho dos dados..
        /// </summary>
        internal static string RETURN_NEG_105 {
            get {
                return ResourceManager.GetString("RETURN_NEG_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID REP não possui o cadastro do empregador..
        /// </summary>
        internal static string RETURN_NEG_11 {
            get {
                return ResourceManager.GetString("RETURN_NEG_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do empregador inválidos: CPF / CNPJ..
        /// </summary>
        internal static string RETURN_NEG_12 {
            get {
                return ResourceManager.GetString("RETURN_NEG_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do empregador inválidos: Nome / Razão Social..
        /// </summary>
        internal static string RETURN_NEG_13 {
            get {
                return ResourceManager.GetString("RETURN_NEG_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do empregador inválidos: Endereço..
        /// </summary>
        internal static string RETURN_NEG_14 {
            get {
                return ResourceManager.GetString("RETURN_NEG_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e/ou hora inválida(s)..
        /// </summary>
        internal static string RETURN_NEG_15 {
            get {
                return ResourceManager.GetString("RETURN_NEG_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no módulo biométrico: ERRO DE ESCRITA..
        /// </summary>
        internal static string RETURN_NEG_16 {
            get {
                return ResourceManager.GetString("RETURN_NEG_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na escrita do módulo biométrico: TIMEOUT..
        /// </summary>
        internal static string RETURN_NEG_17 {
            get {
                return ResourceManager.GetString("RETURN_NEG_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de comunicação inválidos: Endereço IP..
        /// </summary>
        internal static string RETURN_NEG_18 {
            get {
                return ResourceManager.GetString("RETURN_NEG_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de comunicação inválidos: Máscara de sub-rede..
        /// </summary>
        internal static string RETURN_NEG_19 {
            get {
                return ResourceManager.GetString("RETURN_NEG_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de Código de Barras já cadastrado para outro usuário..
        /// </summary>
        internal static string RETURN_NEG_2 {
            get {
                return ResourceManager.GetString("RETURN_NEG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de comunicação inválidos: IP Gateway..
        /// </summary>
        internal static string RETURN_NEG_20 {
            get {
                return ResourceManager.GetString("RETURN_NEG_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao abrir o arquivo .ubs.
        /// </summary>
        internal static string RETURN_NEG_200 {
            get {
                return ResourceManager.GetString("RETURN_NEG_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar o arquivo .ubs.
        /// </summary>
        internal static string RETURN_NEG_201 {
            get {
                return ResourceManager.GetString("RETURN_NEG_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao ler o arquivo .ubs.
        /// </summary>
        internal static string RETURN_NEG_202 {
            get {
                return ResourceManager.GetString("RETURN_NEG_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de checksum dos dados do arquivo .ubs.
        /// </summary>
        internal static string RETURN_NEG_203 {
            get {
                return ResourceManager.GetString("RETURN_NEG_203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao abrir o AFD.
        /// </summary>
        internal static string RETURN_NEG_204 {
            get {
                return ResourceManager.GetString("RETURN_NEG_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao ler o AFD.
        /// </summary>
        internal static string RETURN_NEG_205 {
            get {
                return ResourceManager.GetString("RETURN_NEG_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao fechar o AFD.
        /// </summary>
        internal static string RETURN_NEG_206 {
            get {
                return ResourceManager.GetString("RETURN_NEG_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao manipular o AFD.
        /// </summary>
        internal static string RETURN_NEG_207 {
            get {
                return ResourceManager.GetString("RETURN_NEG_207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao fechar o arquivo .ubs.
        /// </summary>
        internal static string RETURN_NEG_208 {
            get {
                return ResourceManager.GetString("RETURN_NEG_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabeçalho do arquivo .ubs inválido.
        /// </summary>
        internal static string RETURN_NEG_209 {
            get {
                return ResourceManager.GetString("RETURN_NEG_209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem eventos..
        /// </summary>
        internal static string RETURN_NEG_21 {
            get {
                return ResourceManager.GetString("RETURN_NEG_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao escrever no arquivo .ubs.
        /// </summary>
        internal static string RETURN_NEG_210 {
            get {
                return ResourceManager.GetString("RETURN_NEG_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo biométrico cheio..
        /// </summary>
        internal static string RETURN_NEG_22 {
            get {
                return ResourceManager.GetString("RETURN_NEG_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no módulo biométrico: ERRO DE LEITURA..
        /// </summary>
        internal static string RETURN_NEG_23 {
            get {
                return ResourceManager.GetString("RETURN_NEG_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na leitura do módulo biométrico: TIMEOUT..
        /// </summary>
        internal static string RETURN_NEG_24 {
            get {
                return ResourceManager.GetString("RETURN_NEG_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de checksum da área de dados..
        /// </summary>
        internal static string RETURN_NEG_25 {
            get {
                return ResourceManager.GetString("RETURN_NEG_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do empregador inválidos: CEI..
        /// </summary>
        internal static string RETURN_NEG_26 {
            get {
                return ResourceManager.GetString("RETURN_NEG_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipamento bloqueado..
        /// </summary>
        internal static string RETURN_NEG_27 {
            get {
                return ResourceManager.GetString("RETURN_NEG_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do alarme inválido..
        /// </summary>
        internal static string RETURN_NEG_28 {
            get {
                return ResourceManager.GetString("RETURN_NEG_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do produto inválido..
        /// </summary>
        internal static string RETURN_NEG_29 {
            get {
                return ResourceManager.GetString("RETURN_NEG_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIS já cadastrado para outro usuário..
        /// </summary>
        internal static string RETURN_NEG_3 {
            get {
                return ResourceManager.GetString("RETURN_NEG_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereços da comunicação Serial inválidos..
        /// </summary>
        internal static string RETURN_NEG_30 {
            get {
                return ResourceManager.GetString("RETURN_NEG_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de segurança do módulo biométrico inválido..
        /// </summary>
        internal static string RETURN_NEG_31 {
            get {
                return ResourceManager.GetString("RETURN_NEG_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de acesso via teclado já cadastrado para outro usuário..
        /// </summary>
        internal static string RETURN_NEG_4 {
            get {
                return ResourceManager.GetString("RETURN_NEG_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na memória MRP..
        /// </summary>
        internal static string RETURN_NEG_5 {
            get {
                return ResourceManager.GetString("RETURN_NEG_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na memória MT..
        /// </summary>
        internal static string RETURN_NEG_6 {
            get {
                return ResourceManager.GetString("RETURN_NEG_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na memória RAM..
        /// </summary>
        internal static string RETURN_NEG_7 {
            get {
                return ResourceManager.GetString("RETURN_NEG_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados enviados inválidos..
        /// </summary>
        internal static string RETURN_NEG_8 {
            get {
                return ResourceManager.GetString("RETURN_NEG_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID REP não possui trabalhadores cadastrados..
        /// </summary>
        internal static string RETURN_NEG_9 {
            get {
                return ResourceManager.GetString("RETURN_NEG_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido.
        /// </summary>
        internal static string RETURN_UNKNOW {
            get {
                return ResourceManager.GetString("RETURN_UNKNOW", resourceCulture);
            }
        }
    }
}
