unit uConsts;

interface

const
  AGRUPAMENTO_FUNCS_NENHUM = 0;
  AGRUPAMENTO_FUNCS_DEPTO  = 1;
  AGRUPAMENTO_FUNCS_CARGOS = 2;
  AGRUPAMENTO_FUNCS_LOCAL  = 3;

  SGFUNCS_COL_NOME      = 0;
  SGFUNCS_COL_CARGO     = 1;
  SGFUNCS_COL_FUNC      = 2;
  SGFUNCS_COL_DEPTONOME = 3;
  SGFUNCS_COL_PIS       = 4;
  SGFUNCS_COL_TERMINAL_DESCRICAO = 5;
  SGFUNCS_COL_TERMINAL  = 6;

implementation

end.
